Introduction to ML Packages

This tutorial is your gateway to the exciting world of ML packages! 🚀 Instead of diving deep into every feature of each package, we’re here to give you a big-picture view and showcase the purpose of some of the most popular ones out there. Think of it as a teaser to spark your curiosity! For the nitty-gritty details, you can always explore the official docs and dive into other awesome tutorials online. Let’s get started! 🎉

In [ ]:
Jupyter
Jupyter is not strictly speaking an ML package. It provides a browser front-end connected to an instance of IPython which allows REPL for quick testing, allows to create documents that intertwines code, output, images, and text. This is great for prototyping, demonstrations and tutorials, but terrible for actual coding.

In [2]:
6*7

42

In [3]:
def tokenize(text):
    return text.split(" ")

In [4]:
text = "  Generative AI creates new content, like text or images, based on patterns in data.  "
print(tokenize(text))

['', '', 'Generative', 'AI', 'creates', 'new', 'content,', 'like', 'text', 'or', 'images,', 'based', 'on', 'patterns', 'in', 'data.', '', '']


Numpy

Numpy is desiged to handle large multidimensional arrays and enable efficient computations with them. In the back, it runs pre-compiled C code which is much faster than, say, a Python for loop

In the Numpy tutorial, we have covered the basics of Numpy, numpy arrays, element-wise operations, matrices operations and generating random matrices. In this section, we'll cover indexing, slicing and broadcasting, which are useful concepts that will be reused in Pandas and PyTorch.

In [2]:
import numpy as np

Indexing and slicing

Numpy arrays can be indexed and sliced like regular python arrays .

In [7]:
a_py = [1, 2, 3, 4, 5, 6, 7, 8, 9]
a_np = np.array(a_py)

In [8]:
print(a_py[3:7:2], a_np[3:7:2])
print(a_py[2:-1:2], a_np[2:-1:2])
print(a_py[::-1], a_np[::-1])

[4, 6] [4 6]
[3, 5, 7] [3 5 7]
[9, 8, 7, 6, 5, 4, 3, 2, 1] [9 8 7 6 5 4 3 2 1]


But you can also use arrays to index other arrays

In [9]:
idx = np.array([7,2])
a_np[idx] 

array([8, 3])

Which allows convenient querying, reindexing and even sorting .

In [11]:
ages = np.random.randint(low=30, high=60, size=10)
heights = np.random.randint(low=150, high=210, size=10)

print(ages)
print(heights)

[45 41 39 48 33 59 30 36 43 44]
[156 173 190 180 204 184 208 205 169 201]


In [3]:
ages = np.random.randint(low=30, high=60, size=10)
heights = np.random.randint(low=150, high=210, size=10)

print(ages)
print(heights) 

[57 44 51 34 39 51 38 43 47 45]
[156 165 183 208 186 182 196 164 185 207]


In [ ]:
print(ages < 50)